"""Twitch GraphQL client.

Twitch's private GraphQL API only accepts *persisted* queries: you send a SHA-256
hash of a query document that Twitch's own web client ships, not the document
itself. Those hashes rotate whenever Twitch redeploys the player, which is the
single most likely way this bot breaks.

Two things follow from that, and they shape this whole module:

1. **Every hash lives in one registry** (:data:`OPERATIONS`) and every one of them
   is overridable from ``data/gql_operations.json`` without touching code, so a
   rotation is a config edit rather than a patch.
2. **A changed response shape is an error, never a zero.** Reading drop progress
   through a renamed field must not quietly return "0 minutes watched" — that
   would look exactly like a stream that isn't crediting. :func:`pluck` raises
   :class:`SchemaDriftError` instead, which phase 5 surfaces to Discord as
   "Twitch API changed, needs a fix".
"""

from __future__ import annotations

import asyncio
import json
import random
from dataclasses import dataclass, replace
from pathlib import Path
from typing import TYPE_CHECKING, Any

import aiohttp

from .. import paths
from ..events import EventType
from ..log import get_logger

if TYPE_CHECKING:
    from ..config import TwitchConfig
    from ..events import EventBus
    from .auth import AuthManager

log = get_logger("twitch.gql")

GQL_ENDPOINT = "https://gql.twitch.tv/gql"

#: Retried transparently; anything else is surfaced.
RETRY_STATUSES = frozenset({429, 500, 502, 503, 504})


class GQLError(Exception):
    """Base for GraphQL failures."""


class GQLTransportError(GQLError):
    """Network or HTTP-level failure that outlived its retries."""


class SchemaDriftError(GQLError):
    """Twitch's response didn't match what we parse.

    Deliberately distinct from a transport error: this one needs a human to
    update an operation hash or a field path, and retrying will never help.
    """


class PersistedQueryNotFound(SchemaDriftError):
    """The operation hash is stale — Twitch has rotated its query documents."""


class IntegrityChallengeError(GQLError):
    """Twitch demanded a Client-Integrity token this bot cannot produce.

    The integrity header is generated by the real web player specifically to
    distinguish it from automation, and forging it is out of scope — so this is a
    permanent, honest "no" for the operation rather than something to retry.

    Callers should degrade to a manual path and say so plainly. Known to gate
    ``DropsPage_ClaimDropRewards`` and ``ViewerDropsDashboard``.
    """


@dataclass(frozen=True, slots=True)
class Operation:
    """A persisted GraphQL operation.

    ``document`` is an optional raw-query fallback. Twitch accepts raw documents
    for some operations and rejects them for others; when it works it lets the bot
    keep running through a hash rotation instead of going dark.
    """

    name: str
    sha256: str
    version: int = 1
    document: str | None = None
    requires_auth: bool = True

    def persisted_payload(self, variables: dict[str, Any]) -> dict[str, Any]:
        return {
            "operationName": self.name,
            "variables": variables,
            "extensions": {
                "persistedQuery": {"version": self.version, "sha256Hash": self.sha256}
            },
        }

    def document_payload(self, variables: dict[str, Any]) -> dict[str, Any]:
        if not self.document:
            raise SchemaDriftError(f"{self.name}: no raw-document fallback available")
        return {
            "operationName": self.name,
            "variables": variables,
            "query": self.document,
        }


# --------------------------------------------------------------------- registry
#
# Every document below was verified against live Twitch on 2026-07-29, and the
# field names reflect what the schema actually accepts rather than what the
# obvious guess would be. Two that cost a round trip each:
#
#   * ``Channel`` has no ``login`` field — it's ``name``.
#   * ``Game.streams`` takes no ``sortTypeIsRecency`` argument, despite the web
#     client passing one as a top-level query variable.

_DOCS: dict[str, str] = {
    "UseLive": """
query UseLive($channelLogin: String!) {
  user(login: $channelLogin) {
    id
    login
    stream { id type createdAt game { id name } }
  }
}
""",
    "StreamMetadata": """
query StreamMetadata($channelLogin: String!) {
  user(login: $channelLogin) {
    id
    login
    displayName
    stream { id type createdAt viewersCount game { id name } }
  }
}
""",
    "PlaybackAccessToken": """
query PlaybackAccessToken(
  $login: String!
  $isLive: Boolean!
  $vodID: ID!
  $isVod: Boolean!
  $playerType: String!
) {
  streamPlaybackAccessToken(
    channelName: $login
    params: {platform: "web", playerBackend: "mediaplayer", playerType: $playerType}
  ) @include(if: $isLive) { value signature }
  videoPlaybackAccessToken(
    id: $vodID
    params: {platform: "web", playerBackend: "mediaplayer", playerType: $playerType}
  ) @include(if: $isVod) { value signature }
}
""",
    "DropCurrentSessionContext": """
query DropCurrentSessionContext($channelLogin: String) {
  currentUser {
    id
    dropCurrentSession(channelLogin: $channelLogin) {
      channel { id name displayName }
      game { id name }
      dropID
      currentMinutesWatched
      requiredMinutesWatched
    }
  }
}
""",
    "Inventory": """
query Inventory {
  currentUser {
    id
    inventory {
      dropCampaignsInProgress {
        # The account-connection gate. Twitch credits zero minutes when the
        # required external account (Battle.net for Overwatch) is not linked, and
        # says nothing about it anywhere else -- so without this the bot reports
        # a perfectly healthy watch loop earning nothing, forever.
        #
        # accountLinkURL is the page that fixes it, from Twitch rather than
        # hardcoded, because it differs per campaign publisher.
        accountLinkURL
        self { isAccountConnected }
        id
        name
        status
        startAt
        endAt
        game { id name slug }
        timeBasedDrops {
          id
          name
          requiredMinutesWatched
          startAt
          endAt
          self { currentMinutesWatched isClaimed dropInstanceID }
          benefitEdges { benefit { id name imageAssetURL } entitlementLimit }
        }
      }
      gameEventDrops { id name lastAwardedAt totalCount }
    }
  }
}
""",
    # Verified against the live schema, and verified to be *refused*:
    # ClaimDropRewardsPayload exposes `status` (there is no `errors` field), and
    # the mutation answers with an integrity challenge. Kept correct and ready in
    # case Twitch ever stops gating it.
    "DropsPage_ClaimDropRewards": """
mutation DropsPage_ClaimDropRewards($input: ClaimDropRewardsInput!) {
  claimDropRewards(input: $input) { status }
}
""",
    "DirectoryPage_Game": """
query DirectoryPage_Game(
  $slug: String!
  $limit: Int
  $options: GameStreamOptions
  $cursor: Cursor
) {
  game(slug: $slug) {
    id
    displayName
    streams(first: $limit, options: $options, after: $cursor) {
      edges {
        cursor
        node {
          id
          title
          viewersCount
          type
          createdAt
          game { id name }
          broadcaster { id login displayName }
        }
      }
    }
  }
}
""",
}

# Deliberately absent: ``ViewerDropsDashboard``.
#
# It answers "every campaign that exists for this game", and live Twitch rejects it
# with ``failed integrity check`` — it sits behind the Client-Integrity header the
# web player attaches, which is Twitch's anti-automation gate. Working around that
# is not something this bot attempts.
#
# It also isn't needed: ``Inventory`` returns ``dropCampaignsInProgress`` with the
# per-drop minute counts and claim state, which is what tracking and claiming
# actually run on. The only thing lost is browsing not-yet-started campaigns.
#
# If a future operation returns the same error, that's the cause — not a bad hash.

#: Persisted hashes, kept as a secondary path. ``dropwatch gql-check`` reports which
#: are current; a stale one only matters for an operation with no document, and
#: any of them can be corrected via ``data/gql_operations.json``.
_HASHES: dict[str, str] = {
    "UseLive":
        "639d5f11bfb8bf3053b424d9ef650d04c4ebb7d94711d644afb08fe9a0fad5d9",
    "StreamMetadata":
        "059c4653b788f5bdb2ee7870a9fbc7c6e9ba1e4e0bd9d9f4b6b6e0f7b0a8a3d1",
    "PlaybackAccessToken":
        "3093517e37e4f4cb48906155bcd894150aef92617939236d2508f3375ab732ce",
    "DropCurrentSessionContext":
        "4d06b702d25d652afb9ef835d2a550031f1cf762b193523a92166f40ea3d142b",
    "Inventory":
        "37fea486d6179047c41d0f549088a4c3a7dd60c05c70956a1490262f532dccd9",
    "DropsPage_ClaimDropRewards":
        "a455deea71bdc9015b78eb49f4acfbce8baa7ccbedd28e549bb025bd0f751930",
    "DirectoryPage_Game":
        "3c9a94ee095c735e43ed3ad6ce6d4cbd03c4c6f754b31de54993e0d48fd54e30",
}

#: Operations that read nothing account-specific and work without a token.
_ANONYMOUS = frozenset({"UseLive", "StreamMetadata", "DirectoryPage_Game"})

OPERATIONS: dict[str, Operation] = {
    name: Operation(
        name=name,
        sha256=_HASHES.get(name, ""),
        document=_DOCS.get(name),
        requires_auth=name not in _ANONYMOUS,
    )
    for name in _HASHES | _DOCS
}


def load_operation_overrides(path: Path | None = None) -> dict[str, str]:
    """Read ``{"OperationName": "sha256", ...}`` from ``data/gql_operations.json``.

    Exists so a hash rotation can be fixed by editing one JSON file — including
    from a phone, mid-event — rather than shipping a code change.
    """
    target = paths.DATA_DIR / "gql_operations.json" if path is None else path
    try:
        raw = json.loads(target.read_text("utf-8"))
    except FileNotFoundError:
        return {}
    except (OSError, json.JSONDecodeError) as exc:
        log.warning("ignoring unreadable gql_operations.json: %s", exc)
        return {}
    if not isinstance(raw, dict):
        log.warning("gql_operations.json must be an object of name -> hash")
        return {}
    return {str(k): str(v) for k, v in raw.items() if isinstance(v, str)}


def build_registry(overrides: dict[str, str] | None = None) -> dict[str, Operation]:
    ops = dict(OPERATIONS)
    for name, sha in (overrides or {}).items():
        if name in ops:
            if sha != ops[name].sha256:
                log.info("using overridden hash for %s", name)
            ops[name] = replace(ops[name], sha256=sha)
        else:
            log.warning("override for unknown operation %r ignored", name)
    return ops


# ----------------------------------------------------------------- field access


_MISSING = object()


def pluck(data: Any, *path: str | int, default: Any = _MISSING) -> Any:
    """Walk a nested response, raising :class:`SchemaDriftError` on a bad path.

    Pass ``default`` only where absence is genuinely meaningful — ``stream`` being
    ``None`` for an offline channel, say. Everywhere else, let it raise: a silent
    ``None`` from a renamed field is indistinguishable from "no progress", which
    is the exact failure this bot must never hide.
    """
    cursor = data
    for i, key in enumerate(path):
        try:
            cursor = cursor[key]
        except (KeyError, IndexError, TypeError):
            if default is not _MISSING:
                return default
            trail = " -> ".join(str(p) for p in path[: i + 1])
            raise SchemaDriftError(
                f"unexpected response shape at {trail!r} "
                f"(got {type(cursor).__name__})"
            ) from None
    return cursor


# ------------------------------------------------------------------------ client


class GQLClient:
    """Calls persisted GraphQL operations with retry, backoff and drift detection."""

    def __init__(
        self,
        session: aiohttp.ClientSession,
        auth: AuthManager,
        config: TwitchConfig,
        bus: EventBus,
        *,
        operations: dict[str, Operation] | None = None,
    ) -> None:
        self._session = session
        self._auth = auth
        self._config = config
        self._bus = bus
        self._ops = operations if operations is not None else build_registry(
            load_operation_overrides()
        )
        self._sem = asyncio.Semaphore(config.gql_max_concurrency)
        # Ops whose persisted hash Twitch rejected — don't keep paying for a
        # round trip we know will 400 before falling back.
        self._stale: set[str] = set()

    @property
    def operations(self) -> dict[str, Operation]:
        return dict(self._ops)

    @property
    def stale_operations(self) -> set[str]:
        return set(self._stale)

    async def call(
        self,
        operation: str,
        variables: dict[str, Any] | None = None,
        *,
        allow_document_fallback: bool = True,
    ) -> dict[str, Any]:
        """Run one operation and return its ``data`` object."""
        op = self._ops.get(operation)
        if op is None:
            raise GQLError(f"unknown operation {operation!r}")

        vars_ = variables or {}

        # Prefer the document we wrote and verified: persisted hashes rotate on
        # Twitch's schedule and are the known failure mode, whereas a document
        # only breaks if the schema itself changes — which breaks parsing anyway.
        # A hash is still used for operations we have no document for.
        use_document = bool(op.document) and (
            self._config.prefer_documents or operation in self._stale or not op.sha256
        )

        payload = op.document_payload(vars_) if use_document else op.persisted_payload(vars_)

        # _unwrap must be inside the try: a rejected hash is reported as a GraphQL
        # error in the response body, not as an HTTP status, so it surfaces from
        # _unwrap rather than _post. Wrapping only the POST leaves the fallback
        # below unreachable.
        try:
            body = await self._post(payload, op)
            return self._unwrap(body, op)
        except PersistedQueryNotFound:
            if not (allow_document_fallback and op.document and not use_document):
                self._stale.add(operation)
                await self._bus.publish(
                    EventType.SCHEMA_DRIFT,
                    operation=operation,
                    reason="persisted query hash rejected and no document fallback exists",
                )
                raise
            log.warning("%s hash is stale — retrying as a raw document", operation)
            self._stale.add(operation)
            body = await self._post(op.document_payload(vars_), op)
            return self._unwrap(body, op)

    async def _post(self, payload: Any, op: Operation) -> Any:
        headers: dict[str, str] = {"Client-ID": self._config.gql_client_id}
        if op.requires_auth or self._auth.authenticated:
            try:
                token = await self._auth.ensure_valid()
                headers["Authorization"] = f"OAuth {token}"
            except Exception:
                if op.requires_auth:
                    raise

        attempts = self._config.gql_max_retries + 1
        last: Exception | None = None

        for attempt in range(attempts):
            if attempt:
                await asyncio.sleep(self._backoff(attempt))
            async with self._sem:
                try:
                    async with self._session.post(
                        GQL_ENDPOINT, json=payload, headers=headers
                    ) as resp:
                        text = await resp.text()
                        if resp.status in RETRY_STATUSES:
                            last = GQLTransportError(
                                f"{op.name}: HTTP {resp.status}"
                            )
                            log.debug(
                                "%s got %s, retry %d/%d",
                                op.name, resp.status, attempt + 1, attempts,
                            )
                            continue
                        if resp.status == 401:
                            # One forced refresh, then let the next attempt use it.
                            if attempt == 0 and self._auth.authenticated:
                                log.info("%s got 401 — refreshing token", op.name)
                                await self._auth.refresh()
                                token = await self._auth.ensure_valid()
                                headers["Authorization"] = f"OAuth {token}"
                                last = GQLTransportError(f"{op.name}: HTTP 401")
                                continue
                            raise GQLTransportError(f"{op.name}: unauthorised")
                        if resp.status >= 400:
                            raise GQLTransportError(
                                f"{op.name}: HTTP {resp.status}: {text[:200]}"
                            )
                        try:
                            return json.loads(text)
                        except json.JSONDecodeError as exc:
                            raise SchemaDriftError(
                                f"{op.name}: response was not JSON: {text[:200]}"
                            ) from exc
                except (TimeoutError, aiohttp.ClientError) as exc:
                    last = GQLTransportError(f"{op.name}: {exc}")
                    log.debug(
                        "%s transport error, retry %d/%d: %s",
                        op.name, attempt + 1, attempts, exc,
                    )

        raise last or GQLTransportError(f"{op.name}: exhausted retries")

    def _backoff(self, attempt: int) -> float:
        """Exponential with full jitter, so concurrent callers don't resynchronise."""
        ceiling = min(
            self._config.gql_backoff_base * (2 ** (attempt - 1)),
            self._config.gql_backoff_max,
        )
        return random.uniform(0, ceiling)

    def _unwrap(self, body: Any, op: Operation) -> dict[str, Any]:
        # Twitch returns a bare object for one op and a list when batching.
        if isinstance(body, list):
            body = body[0] if body else {}
        if not isinstance(body, dict):
            raise SchemaDriftError(f"{op.name}: expected an object, got {type(body).__name__}")

        # Checked before `errors`: an integrity challenge also emits a generic
        # error, and reporting that instead would send someone chasing a schema
        # problem that doesn't exist.
        challenge = pluck(body, "extensions", "challenge", "type", default=None)
        if challenge == "integrity":
            raise IntegrityChallengeError(
                f"{op.name}: Twitch requires a Client-Integrity token for this "
                "operation, which this bot does not produce"
            )

        errors = body.get("errors")
        if errors:
            messages = [
                str(e.get("message", e)) if isinstance(e, dict) else str(e) for e in errors
            ]
            joined = "; ".join(messages)
            if any("PersistedQueryNotFound" in m for m in messages):
                raise PersistedQueryNotFound(f"{op.name}: {joined}")
            raise GQLError(f"{op.name}: {joined}")

        data = body.get("data")
        if data is None:
            raise SchemaDriftError(f"{op.name}: response contained no data")
        return data
